import { Timestamp } from 'firebase/firestore';

function ts(minutesAgo) {
  return { toDate: () => new Date(Date.now() - minutesAgo * 60000) };
}

export const MOCK_CALLS = [
  {
    id: 'mock-1',
    status: 'answered',
    callerName: 'Sarah Mitchell',
    callerNumber: '+61 412 345 678',
    callerEmail: 'sarah@example.com',
    duration: 184,
    intent: 'booking',
    summary: 'Called to book a consultation for next Tuesday at 2pm. Confirmed availability and sent follow-up email.',
    transcript: [
      { role: 'assistant', content: 'Thank you for calling, this is Aria — how can I help you today?' },
      { role: 'user',      content: 'Hi, I\'d like to book a consultation please.' },
      { role: 'assistant', content: 'Of course! I\'d be happy to help you with that. What day works best for you?' },
      { role: 'user',      content: 'Next Tuesday if possible, around 2pm?' },
      { role: 'assistant', content: 'Tuesday at 2pm looks great — I\'ve got that slot available. Can I take your name and email to confirm the booking?' },
      { role: 'user',      content: 'Sure, it\'s Sarah Mitchell — sarah@example.com.' },
      { role: 'assistant', content: 'Perfect, Sarah! I\'ve booked you in for Tuesday at 2pm and you\'ll receive a confirmation email shortly. Is there anything else I can help with?' },
      { role: 'user',      content: 'No that\'s great, thank you!' },
      { role: 'assistant', content: 'Wonderful — we\'ll see you Tuesday. Have a great day!' },
    ],
    createdAt: ts(12),
  },
  {
    id: 'mock-2',
    status: 'answered',
    callerName: 'James O\'Brien',
    callerNumber: '+61 423 987 654',
    duration: 97,
    intent: 'enquiry',
    summary: 'Asked about pricing for the premium plan and whether there\'s a free trial. Directed to website and offered callback.',
    transcript: [
      { role: 'assistant', content: 'Thanks for calling! How can I help?' },
      { role: 'user',      content: 'Yeah hi, I wanted to ask about your pricing — do you have a free trial?' },
      { role: 'assistant', content: 'Great question! Yes, we offer a 7-day free trial on all plans, no credit card required. Our premium plan starts at $99/month after that.' },
      { role: 'user',      content: 'And what\'s included in the premium plan?' },
      { role: 'assistant', content: 'The premium plan includes unlimited AI operators, full CRM integration, priority support, and custom branding. Would you like me to send you the full plan comparison to your email?' },
      { role: 'user',      content: 'Yes please, it\'s james@obrien.com.' },
      { role: 'assistant', content: 'Done! You\'ll receive that within a few minutes. Anything else I can help with?' },
    ],
    createdAt: ts(45),
  },
  {
    id: 'mock-3',
    status: 'missed',
    callerName: 'Unknown caller',
    callerNumber: '+61 498 111 222',
    duration: 0,
    intent: null,
    summary: null,
    transcript: [],
    createdAt: ts(62),
  },
  {
    id: 'mock-4',
    status: 'answered',
    callerName: 'Priya Sharma',
    callerNumber: '+61 401 567 890',
    callerEmail: 'priya.sharma@gmail.com',
    duration: 231,
    intent: 'support',
    summary: 'Reported an issue with her account login. Walked through password reset steps. Issue resolved on the call.',
    transcript: [
      { role: 'assistant', content: 'Hi there, you\'ve reached support — how can I help you today?' },
      { role: 'user',      content: 'I can\'t log into my account, it keeps saying incorrect password.' },
      { role: 'assistant', content: 'I\'m sorry to hear that, Priya. Let\'s get that sorted for you right now. Have you tried the "Forgot Password" link on the login page?' },
      { role: 'user',      content: 'No I haven\'t, I didn\'t see it.' },
      { role: 'assistant', content: 'No worries! If you go to the login page, there\'s a small "Forgot?" link just below the password field. Click that and enter your email — you\'ll get a reset link within 2 minutes.' },
      { role: 'user',      content: 'Oh I see it now... okay I\'ve clicked it. Yes, I just got the email!' },
      { role: 'assistant', content: 'Excellent! Follow that link, set a new password, and you should be all good. Would you like to stay on the line while you do that?' },
      { role: 'user',      content: 'That\'s okay, I\'m in now. Thank you so much!' },
      { role: 'assistant', content: 'Brilliant — glad we got that sorted! Have a great rest of your day.' },
    ],
    createdAt: ts(130),
  },
  {
    id: 'mock-5',
    status: 'voicemail',
    callerName: 'Tom Fletcher',
    callerNumber: '+61 477 333 444',
    duration: 28,
    intent: 'enquiry',
    summary: 'Left a voicemail asking about delivery times for bulk orders.',
    transcript: [
      { role: 'user', content: 'Hi, this is Tom from Fletcher & Co. I was calling to ask about delivery times for bulk orders. Could someone call me back on this number? Thanks.' },
    ],
    createdAt: ts(240),
  },
  {
    id: 'mock-6',
    status: 'answered',
    callerName: 'Emma Lawson',
    callerNumber: '+61 455 778 990',
    duration: 156,
    intent: 'booking',
    summary: 'Rescheduled existing appointment from Wednesday to Friday at 10am. Confirmed and updated the booking.',
    transcript: [
      { role: 'assistant', content: 'Thanks for calling! How can I help you today?' },
      { role: 'user',      content: 'Hi, I need to reschedule my appointment that\'s on Wednesday.' },
      { role: 'assistant', content: 'Of course — can I get your name so I can pull up the booking?' },
      { role: 'user',      content: 'It\'s Emma Lawson.' },
      { role: 'assistant', content: 'Thanks Emma! I can see your appointment on Wednesday at 3pm. When would you like to move it to?' },
      { role: 'user',      content: 'Would Friday at 10am work?' },
      { role: 'assistant', content: 'Friday at 10am is available — I\'ve moved your appointment. You\'ll get a confirmation text shortly. Anything else?' },
      { role: 'user',      content: 'No that\'s perfect, thanks!' },
    ],
    createdAt: ts(380),
  },
  {
    id: 'mock-7',
    status: 'missed',
    callerName: 'Daniel Park',
    callerNumber: '+61 488 654 321',
    duration: 0,
    intent: null,
    summary: null,
    transcript: [],
    createdAt: ts(500),
  },
  {
    id: 'mock-8',
    status: 'answered',
    callerName: 'Rachel Green',
    callerNumber: '+61 412 999 888',
    duration: 112,
    intent: 'complaint',
    summary: 'Frustrated about a delayed order. Apologised and escalated to fulfilment team. Offered 10% discount on next order.',
    transcript: [
      { role: 'assistant', content: 'Hi, thanks for calling — how can I help?' },
      { role: 'user',      content: 'I\'m really frustrated. My order was supposed to arrive 3 days ago and it still hasn\'t shown up.' },
      { role: 'assistant', content: 'I completely understand your frustration, Rachel, and I\'m sorry for the delay. That\'s not the experience we want for you. Let me look into this right away.' },
      { role: 'user',      content: 'I needed it for an event last weekend. It\'s too late now.' },
      { role: 'assistant', content: 'I\'m so sorry — I can see the delay was on our end. I\'ve flagged this as urgent with our fulfilment team and they\'ll contact you within the hour. I\'d also like to offer you 10% off your next order as an apology.' },
      { role: 'user',      content: 'Okay, I appreciate that. Thank you.' },
    ],
    createdAt: ts(680),
  },
];

export const MOCK_VOICE_CONFIG = {
  botName: 'Aria',
  businessName: 'Freemi Demo',
  phoneNumber: '+61 2 9999 0000',
  active: true,
  greeting: 'Thank you for calling Freemi Demo, this is Aria — how can I help you today?',
};
